server:
  port: 8001
  servlet:
    context-path: /customer

spring:
  application:
    name: cloud-customer-service
  jackson:
    property-naming-strategy: SNAKE_CASE  #json输出驼峰变成下划线加小写

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://rm-bp15qb6d0jd02q7k4qo.mysql.rds.aliyuncs.com:3306/cloud_consumer?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: sb
    password: Hahahaha!


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版

#设置feign 客户端超时时间（openFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
      #feign日志以什么级别监控哪个接口
    com.yzc.springcloud.feign.OrderFeign: debug

mybatis:
  type-aliases-package: com.yzc.springcloud.entity # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml # mapper映射文件
mybatis-plus:
  mapper-locations: classpath:com/yzc/springcloud/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true
