server:
  port: 2001

spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: 1.117.54.209:1111
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp15qb6d0jd02q7k4qo.mysql.rds.aliyuncs.com:3306/cloud_branch?serverTimezone=GMT%2b8
    username: sb
    password: Hahahaha!

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml