server:
  port: 8003
  servlet:
    context-path: /order

spring:
  application:
    name: cloud-order-service
  jackson:
    property-naming-strategy: SNAKE_CASE  #json输出驼峰变成下划线加小写
  main:
    allow-bean-definition-overriding: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver   #mysql驱动包
    url: jdbc:mysql://rm-bp15qb6d0jd02q7k4qo.mysql.rds.aliyuncs.com:3306/cloud_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: sb
    password: Hahahaha!
  redis:
    host: yzcorxh.top
    port: 6379
    password: yzc1998
    timeout: 20000
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
  rabbitmq:
    host: yzcorxh.top
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: order2
    prefer-ip-address: true #访问路径可以显示IP地址

#设置feign 客户端超时时间（openFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

mybatis:
  type-aliases-package: com.yzc.springcloud.entity # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml # mapper映射文件
mybatis-plus:
  mapper-locations: classpath:com/yzc/springcloud/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

