server:
  port: 9999

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: order #   #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://cloud-order-service  #匹配后提供服务的路由地址
          predicates:
            - Path=/order/**          #断言，路径相匹配的进行路由

        - id: user #  #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://cloud-user-service    #匹配后提供服务的路由地址
          predicates:
            - Path=/user/**             #断言，路径相匹配的进行路由

        - id: customer #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://cloud-customer-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/customer/**          #断言，路径相匹配的进行路由
            #- After=2020-03-15T15:35:07.412+08:00[GMT+08:00]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Host=**.atguigu.com
            #- Method=GET
            #- Query=username, \d+ #要有参数名username并且值还要啥整数才能路由
ribbon:
  eager-load:
    enabled: true

eureka:
  instance:
    hostname: gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群版