server:
  port: 8004
  servlet:
    context-path: /user

spring:
  application:
    name: cloud-user-service
  jackson:
    property-naming-strategy: SNAKE_CASE  #json输出驼峰变成下划线加小写

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver        #mysql驱动包
    url: jdbc:mysql://rm-bp15qb6d0jd02q7k4qo.mysql.rds.aliyuncs.com:3306/cloud_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
    username: sb
    password: Hahahaha!
  redis:
    host: 1.117.54.209
    port: 6379
    password: yzc1998
    timeout: 20000
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
  rabbitmq:
    host: 1.117.54.209
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://@eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: userOne
    prefer-ip-address: true #访问路径可以显示IP地址
    #发送心跳时间
    lease-renewal-interval-in-seconds: 3
    #服务端收到心跳后等待时间上线  默认90秒  超时剔除
    lease-expiration-duration-in-seconds: 5


#设置feign 客户端超时时间（openFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

mybatis:
  type-aliases-package: com.yzc.springcloud.entity # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml # mapper映射文件
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: state  #指定逻辑删除字段
      logic-delete-value: 1      #删除后字段值
      #logic-not-delete-value: 0
  mapper-locations: classpath:com/yzc/springcloud/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

